apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp-frontend
  labels:
    app: registerapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registerapp-frontend
  template:
    metadata:
      labels:
        app: registerapp-frontend
    spec:
      containers:
      - name: frontend
        image: 264570364318.dkr.ecr.ap-south-1.amazonaws.com/register-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # frontend port
