alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'jeevanithya5@gmail.com'
      smtp_auth_username: 'jeevanithya5@gmail.com'
      smtp_auth_password: 'YOUR_APP_PASSWORD'  # 16-char Gmail App Password

    route:
      receiver: 'email-alert'

    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'jeevabharathi2602@gmail.com'
            send_resolved: true
            require_tls: true   # <-- this is required
