apiVersion: v1
kind: Service
metadata:
  name: mysql # headless service name
  namespace: my3tier # namespace where mysql is deployed
spec:
  clusterIP: None # headless service
  selector:
    app: mysql
  ports:
    - port: 3306
      name: mysql
